app2/urls.py
from django.urls import path
from app2.views import *
app_name='something'
urlpatterns=[
    path('second/',second,name='second')
]

app3/urls.py
from django.urls import path
from app3.views import *
app_name='nothing'
urlpatterns=[
    path('third/',third,name='third'),
    path('four/',four,name='four'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import app2,app3
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
    path('app3/',include('app3.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'second.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'third.html')

def four(request):
    return render(request,'four.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to First Page</h1>
        <a href="{% url 'first' %}"></a>
    </center>
</body>
</html>

templates/four.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to fourth page</h1>
        <a href="{% url 'nothing:third' %}">navigate to third</a>
    </center>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Second Page</h1>
        <a href="{% url 'nothing:third' %}">navigate to third</a>
        
    </center>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to third page</h1>
        <a href="{% url 'nothing:four' %}">navigate to four</a>
    </center>
</body>
</html>